// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xctlqlbcsezhdulsgbzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjdGxxbGJjc2V6aGR1bHNnYnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzI5NDIsImV4cCI6MjA2NjUwODk0Mn0.FgXl1FDoD2oEi1ZPPBCPfvtTgosVhh85CHI96UZQp-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);